version: '3'
services:
  app:
    container_name: ApiGateway
    volumes:
      - .:/app
    restart: always
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - redis
      - authBackend
  authBackend:
    container_name: AuthBackend
    image: back-app:latest
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  redis:
    container_name: RedisDB
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
  mongo:
    container_name: AuthDB
    image: mongo:4.2
    restart: always
    ports:
      - '27017:27017'